-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 26, 2023 at 09:28 AM
-- Server version: 10.4.22-MariaDB
-- PHP Version: 8.1.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `library`
--

-- --------------------------------------------------------

--
-- Table structure for table `book`
--

CREATE TABLE `book` (
  `ID` int(11) NOT NULL,
  `Name` varchar(100) NOT NULL,
  `Category` varchar(100) NOT NULL,
  `PublishDate` date NOT NULL,
  `Author` varchar(100) NOT NULL,
  `Description` varchar(1000) NOT NULL,
  `ISBNNumber` varchar(100) NOT NULL,
  `Image` text NOT NULL,
  `PublishPlace` varchar(100) NOT NULL,
  `Price` decimal(10,0) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `book`
--

INSERT INTO `book` (`ID`, `Name`, `Category`, `PublishDate`, `Author`, `Description`, `ISBNNumber`, `Image`, `PublishPlace`, `Price`) VALUES
(4, 'Power Parenting: Motivasi Anak Pintar', 'General', '2023-01-23', 'Tengku Asmadi', 'Setiap ibu bapa', '9789830976099', 'MotivasiAnakPintar.jpg', 'Selangor', '35'),
(5, 'mawar', 'General', '2023-01-26', 'kamil', 'bunga bunga malaysia', '142578', 'mawar.jpg', 'Selangor', '22'),
(6, 'A BANKING THOROUGHBRED', 'Social Science', '2007-01-01', 'ZHENG HONG PIAO DATUK PADDY BOWIE', 'Tan Sri Dato’Sri Dr. Teh Hong Piow, Founder and Chairman of Public Bank was born, according to the Chinese Lunar Calendar with its 12-year cycle of animal symbols –in the Year of the Horse. He was to prove a veritable thoroughbred. The term ‘thoroughbred’ is reserved for the noblest of the species-a horse of outstanding quality – commanding speed and strength. In racing terms the most prize winning and the most prized.It is a remarkable man, Tan Sri Dato’ Sri Dr. The Hong Piow –A Banking Thoroughbred. ', '983-99722-7-6', 'A BANKING THOROUGHBRED.jpg', 'KUALA LUMPUR', '30'),
(7, 'A COMPREHENSIVE GUIDE TO MALAYSIAN TAXATION', 'General', '2013-01-03', 'JEYAPALAN KASIPILLAI', 'A GUIDE TO MALAYSIAN TAXATION is an all-inclusive book covering every aspect of basic taxation. The foundation of the work is legislation extracted from the Income Tax Act 1967. It covers all the latest amendments including those arising from the Budget 2013 and recently issued exemption orders.', '983-2679-99-0', 'A COMPREHENSIVE GUIDE TO MALAYSIAN TAXATION.jpg', 'SELANGOR', '120'),
(8, 'A Touch of Greatness ', 'Philosophy', '1999-01-01', 'FRANK TIBOLT', 'One of the “master motivators” before it became the “in” thing to be was a man by the name of Frank Tibolt, and he spent over 50 years teaching people to be successful by getting in touch with their own “inner greatness”.', '967-69-0137-7', 'A Touch of Greatness .jpg', 'BATU CAVES, SELANGOR', '25'),
(9, 'ADVANCED ACCOUNTING', 'Technology', '2005-01-01', 'SHAARI ISA', 'This book is written with the aim of fulfilling part of the needs for local materials in advanced accounting. It is a development of existing accounting materials at the intermediate level. It should be suitable for students preparing themselves for the final year financial accounting examinations in the institutes of higher learning. Because the contents of the book go slightly beyond those which are usually included in the final year bachelor degree accounting courses in local universities, it should be suitable for those who are preparing themselves for the final part of the professional financial accounting courses and for those in more advanced level accounting courses such as the master programs. Those attending accounting courses, workshops and seminars should also find the book useful. Lastly it is also hoped that the book is able to provide additional useful reference material for those who are in practice.', '983-3205-15-1', 'ADVANCED ACCOUNTING.jpg', 'KUALA LUMPUR', '32'),
(10, 'Analysis and Design of Heating, Ventilating, and Air-Conditioning Systems, Second Edition', 'Technology', '2019-12-04', 'Herbert W. Stanford IIIAdam F. Spach', 'nalysis and Design of Heating, Ventilating, and Air-Conditioning Systems, Second Edition, provides a thorough and modern overview of HVAC for commercial and industrial buildings, emphasizing energy efficiency. This text combines coverage of heating and air conditioning systems design with detailed information on the latest controls technologies. It also addresses the art of HVAC design along with carefully explained scientific and technical content, reflecting the extensive experience of the authors. Modern HVAC topics are addressed, including sustainability, IAQ, water treatment and risk management, vibration and noise mitigation, and maintainability from a practical point of view.', '9781138602410', 'Analysis and Design of Heating, Ventilating, and Air-Conditioning Systems, Second Edition.jpg', 'Boca Raton, Florida', '1332'),
(11, 'ANALYSIS FOR FINANCIAL MANAGEMENT', 'Technology', '2011-02-12', 'ROBERT C. HIGGINS', 'Analysis for Financial Management, 10e presents standard techniques and modern developments in a practical and intuitive manner with an emphasis on the managerial applications of financial analysis. It is intended for non-financial managers and business students interested in the practice of financial management.', '0-07-116447-2', 'ANALYSIS FOR FINANCIAL MANAGEMENT.jpg', 'BOSTON', '214'),
(12, 'Android For Beginners: Learn Step by step', 'General', '2019-12-09', 'Guleria, Pratiyush ', 'The book has been written in such a way that the concepts are explained in detail, giving adequate emphasis on examples. To make clarity of the programming examples, logic is explained properly as well as discussed using comments in program itself. The book covers the topics right from the Introduction of the Android Studio and writing programs into it. The Android topics are discussed in detail taking into consideration the practical examples from simple to complex for the better understanding of students.', '9789388176231', 'Android For Beginners: Learn Step by step.jpg', 'New Delhi', '130'),
(13, 'AutoCAD For Dummies For Dummies ComputerTech', 'Technology', '2022-12-03', 'Grabowski, Ralph ', 'Ever started an AutoCAD project, only to give up when you couldn’t quite get the hang of it? Or do you have a project coming up that would really benefit from a few meticulously created drawings? Then you need the latest edition of AutoCAD For Dummies, the world’s bestselling retail book about the wildly popular program.', '9781119868767', 'AutoCAD For Dummies For Dummies ComputerTech.jpg', 'Hoboken, NJ', '110'),
(14, 'BIAR PUTIH TULANG', 'Social Science', '1998-01-01', 'A. KADIR JASIN', 'Columns on political, social, religious, and cultural issues in Malaysia; previously published in Berita harian daily under pen name Kunta Kinte, 1987-1993.', '983-100-057-9', 'BIAR PUTIH TULANG.jpg', 'KUALA LUMPUR', '0'),
(15, 'Business Ethics', 'Philosophy', '2018-01-06', 'Khalidah Khalid Ali et al.', 'his comprehensive second edition caters for undergraduate students pursuing business and accountancy courses at local institutions of higher learning. It is a timely book which offers in-depth discussions on business ethics fundamentals from a local perspective.Spanning 12 chapters, the book starts off with the key concepts and theories of business ethics, followed by important topics such as ethical leadership and corporate culture, corporate governance, corporate social responsibility (CSR), business ethics and information technology (IT), ethics and the environment, as well as ethics in the global environment. What sets this book apart in the market is the inclusion of uncommonly discussed topics, namely consumer ethics and ethics from Islamic perspectives.Students will be able to relate what they have learned to the real world with ease through the various, authentic ‘Cases for Review’ that punctuate the topics covered in the chapters. Each chapter also ends with a glossary of the ', '9789834726218', 'Business Ethics.jpg', 'Shah Alam, Selangor', '53'),
(16, 'Business Law. 3rd Edition.', 'Social Science', '2020-01-09', 'Lee M. P and Ivan J. D', 'This is an introductory textbook on business law tailored for Business and Banking undergraduates. It is aimed at equipping students with essential legal knowledge. The legal principles affecting and shaping business and industries in Malaysia are presented in an accessible manner. The text is written in line with the syllabuses of Business Law courses at  local institutions of higher learning, and comprises recent cases to keep it current and relevant.', '9789834726560', 'Business Law. 3rd Edition..jpg', 'Shah Alam, Selangor', '64'),
(17, 'Business Mathematics for UITM 6th Edition', 'Technology', '2019-01-01', 'Lau Too Kya et al.', 'Business Mathematics is specially written for first and second year students who are pursuing diploma and degree courses in business studies, banking investment analysis, public administration, tourism management, culinary arts, office management and business administration. This book is also suitable for students following off-campus courses and distance learning programmes. Students who are pursuing professional courses such as finance, business administration, commerce and accountancy may also find this book relevant and useful.', '9789834729578', 'Business Mathematics for UITM 6th Edition.jpg', 'Shah Alam, Selangor', '43'),
(18, 'Cabling The Complete Guide to Copper and Fiber-Optic Networking', 'Technology', '2014-10-03', 'Andrew Oliviero and Bill Woodward', 'Fully updated for the growing demand of fiber optics for large-scale communications networks and telecommunication standards, this new edition is organized into two parts. Part I covers LAN Networks and Cabling Systems offers comprehensive coverage on current cabling methodologies and is updated to the latest industry standards. Part II addresses Fiber-Optic Cabling and Components probes deeper into fiber optics and can be used to prepare for the Fiber Optics Installer (FOI) and/or Fiber Optics Technician (FOT) certifications two of the Electronic Technician Associations leading certifications.', '9781118807323', 'Cabling The Complete Guide to Copper and Fiber-Optic Networking.jpg', 'Indianapolis, Indiana', '404'),
(19, 'Case Studies In Finance Managing For Corporate Value Creation', 'Technology', '2013-01-18', 'MC GRAW HILL', 'Case Studies in Finance links managerial decisions to capital markets and the expectations of investors. At the core of almost all of the cases is a valuation task that requires students to look to financial markets for guidance in resolving the case problem. The focus on value helps managers understand the impact of the firm on the world around it. These cases also invite students to apply modern information technology to the analysis of managerial decisions.', '9780071239226', 'Case Studies In Finance Managing For Corporate Value Creation.jpg', 'BOSTON', '111'),
(20, 'CASES IN FINANCIAL MANAGEMENT', 'Technology', '2016-12-13', 'IQBAL MATHUR FREDERICK C. SCHERR', 'N/A', '0-02-377260-3', 'CASES IN FINANCIAL MANAGEMENT.jpg', 'KANADA', '40'),
(21, 'China in the World Contemporary Issues and Perspectives', 'Social Science', '2018-01-01', 'EMILE KOK - KHENG YEOH JOANNE HOI - LEE LOH', 'Since launching the policy of “open and reform” in the late 1970s with the overall aim to encourage the modernization of the Chinese economy while maintaining an at least nominally socialist structure, China has achieved levels of economic growth that were nothing less than miraculous. The growth of China’s income per capita is much faster than that of any other region in the world. The profound changes experienced by China in the recent decades are due both to the dramatic economic reform launched by Deng Xiaoping and the country’s single-mindedness to bring to fruition her “third revolution”. Under this open-door policy, the Chinese economy has gradually reduced the scope of mandatory planning which gave way to greater decentralization and the adoption of a free market system. Externally, China’s new foreign policy orientation governing the conduct of her relations with the surrounding countries seems to have served much to reassure her southern neighbours in ASEAN that the objective', '978-967-5148-07-1', 'China in the World Contemporary Issues and Perspectives.jpg', 'KUALA LUMPUR', '0'),
(22, 'Collins Workplace English (Collins English for Business)', 'Technology', '2012-06-07', 'Schofield, J', 'Learn English with Tom Field, a project manager at Lowis Engineering. He attends meetings, gives short presentations, participates in video and phone conferences and writes emails for different business situations.', '9780007431991', 'Collins Workplace English (Collins English for Business).jpeg', 'London', '99'),
(23, 'Communication for Business and the Professions 7th Edition', 'Technology', '2021-09-01', 'Dwyer, J', 'his text has been written for students studying in Australia who are seeking to enhance their communication skills and opportunities for employment and career progression within businesses, organisations and the professions.', '9781488620782', 'Communication for Business and the Professions 7th Edition.jpg', 'Melbourne, VIC', '320'),
(24, 'COMPUTER ORGANIZATION AND ARCHITECTURE 5th ed', 'General', '2018-03-20', 'WILLIAM STALLINGS', 'The Essentials of Computer Organization and Architecture was awarded a ', '0-13-085263-5', 'COMPUTER ORGANIZATION AND ARCHITECTURE 5th ed.jpg', 'LONDON', '359'),
(25, 'Computer Organization and Design RISC-V Edition The Hardware Software Interface 2nd edition', 'Technology', '2017-04-27', ' Hennessy, Patterson ', 'The new RISC V Edition of Computer Organization and Design features the RISC V open source instruction set architecture, the first open source architecture designed to be used in modern computing environments such as cloud computing, mobile devices, and other embedded systems.', '9780128203316', 'Computer Organization and Design RISC-V Edition The Hardware Software Interface 2nd edition.jpg', 'United States', '366'),
(26, 'Computer Security Fundamental 4th edition', 'General', '2019-10-22', 'William (Chuck) Easttom', 'This guide covers web attacks, hacking, spyware, network defense, security appliances, VPNs, password use, and much more. Its many tips and examples reflect new industry trends and the state-of-the-art in both attacks and defense. Exercises, projects, and review questions in every chapter help you deepen your understanding and apply all you’ve learned.', '9780135774779', 'Computer Security Fundamental 4th edition.jpg', 'Indianapolis, Indiana', '277'),
(27, 'Computer Systems Digital Design Fundamentals of Computer Architecture and ARM Assembly Language 2nd ', 'Technology', '2017-11-08', ' Elahi, Ata ', 'This textbook covers digital design, fundamentals of computer architecture, and assembly language. The book starts by introducing basic number systems, character coding, basic knowledge in digital design, and components of a computer. The book goes on to discuss information representation in computing; Boolean algebra and logic gates; sequential logic; input/output; and CPU performance. The author also covers ARM architecture, ARM instructions and ARM assembly language which is used in a variety of devices such as cell phones, digital TV, automobiles, routers, and switches. The book contains a set of laboratory experiments related to digital design using Logisim software; in addition, each chapter features objectives, summaries, key terms, review questions and problems. The book is targeted to students majoring Computer Science, Information System and IT and follows the ACM/IEEE 2013 guidelines.', '9783030934484', 'Computer Systems Digital Design Fundamentals of Computer Architecture and ARM Assembly Language 2nd Edition.jpg', 'United States', '272'),
(28, 'CORPORATE FINANCE AND INVESTMENT DECISION AND STRATEGIES', 'Technology', '2012-01-01', 'RICHARD PIKE BILL NEALE', 'Corporate Finance and Investments, now in its seventh edition, is a popular and well-regarded text for students of corporate finance. The text takes a practical approach, focusing on the strategic issues of finance in a business setting. With clear and accessible language and an international perspective, the seventh edition will provide students with both essential knowledge of corporate finance and the tools to apply it. Previous page', '0-13-853144-7', 'CORPORATE FINANCE AND INVESTMENT DECISION AND STRATEGIES.jpg', 'LONDON', '43'),
(29, 'CORPORATE FINANCE CONCEPTS & APPLICATIONS', 'Technology', '1985-01-01', 'R. FRANK JULIAN', 'N/a', '0-534-04095', 'CORPORATE FINANCE CONCEPTS & APPLICATIONS.jpg', 'USA', '50'),
(30, 'COST ACCOUNTING WITH BASIC COST MANAGEMENT', 'Technology', '2001-01-01', 'PRABIR DAS', 'N/a', '967-65-5836-2', 'COST ACCOUNTING WITH BASIC COST MANAGEMENT.jpg', 'SHAH ALAM', '0'),
(31, 'Database Systems:  A Practical Approach to Design Implementation and Management', 'General', '2014-01-08', 'THOMAS CONNOLLY CAROLYN BEGG', 'Database Systems is ideal for a one- or two-term course in database management or database design in an undergraduate or graduate level course. With its comprehensive coverage, this book can also be used as a reference for IT professionals.  This best-selling text introduces the theory behind databases in a concise yet comprehensive manner, providing database design methodology that can be used by both technical and non-technical readers. The methodology for relational Database Management Systems is presented in simple, step-by-step instructions in conjunction with a realistic worked example using three explicit phases―conceptual, logical, and physical database design.', '0-201-34287-1', 'Database Systems:  A Practical Approach to Design Implementation and Management.jpg', 'ENGLAND', '0'),
(32, 'Develop Your Presentation Skill: How To Inspire and Inform With Clarity and Confidence', 'Technology', '2019-07-30', 'Theo Theobald', 'Develop Your Presentation Skills offers step-by-step advice to prepare effectively and nail that presentation. Going beyond just handling nerves and presenting slides, this quick and easy guide provides a practical toolkit for developing a winning presentation and improving your confidence along the way. From unpicking the original brief and understanding just what the audience wants, to facing your performance demons and constructing compelling content, you will keep your audience rapt with attention.', '9780749486358', 'Develop Your Presentation Skill: How To Inspire and Inform With Clarity and Confidence.jpg', 'London ; New York', '49'),
(33, 'FINANCIAL ACCOUNTING & REPORTING IN MALAYSIA VOL.2', 'Technology', '2020-10-01', 'TAN LIONG TONG', 'Financial Accounting and Reporting in Malaysia explains clearly the Conceptual Framework used in the preparation of ﬁnancial statements for entities, including groups of companies, and how to analyse and interpret those ﬁnancial statements. With a clear emphasis on local practices, accounting principles are discussed in detail to guide users on the preparation and presentation of ﬁnancial statements to ensure compliance with the latest accounting pronouncements. Where applicable, comparisons are also made with statutory requirements and guidelines issued by the Securities Commission and the Central Bank of Malaysia. In addition, focus is given to providing sample comprehensive disclosures of the MFRSs that may serve as guidelines for company practices. Principles and issues are summarised, explained and demonstrated with illustrative questions and answers in each accounting chapter of this issues-based book.', '983-9274-18-X', 'FINANCIAL ACCOUNTING & REPORTING IN MALAYSIA VOL.2.png', 'KUALA LUMPUR', '0'),
(34, 'FINANCIAL ACCOUNTING & REPORTING IN MALAYSIA', 'Technology', '2017-02-01', 'TAN LIONG TONG', 'The 8th edition of Financial Accounting and Reporting in Malaysia (Volume 1) aims to develop knowledge and skills in understanding and applying the MFRSs, IFRSs and MPERS. With a clear emphasis on local practices, accounting principles are discussed in detail to guide users on the preparation and presentation of financial statements to ensure compliance with the latest requirements. ', '983-9274-14-7', 'FINANCIAL ACCOUNTING & REPORTING IN MALAYSIA.jpg', 'KUALA LUMPUR', '0'),
(35, 'Financial Management (3rd Edition)', 'Technology', '2017-01-01', 'Ng Kean Kok Zhang Weina Maran Marimuthu Sandeep Bhattacharya ', 'This book is written for undergraduates of business courses in which Financial Management is one of the compulsory subjects. In this edition, each chapter has been carefully reviewed and thoroughly revised to reflect the most relevant data and critical issues in financial management, such as risk, return and portfolio management, banking regulations and Basel guidelines. Through additional Further Reading and Further Comments in each chapter, students are taught how to integrate theory with practice in evaluating financial decisions. This edition also includes many new worked out examples to support student problem solving. Additional discussion and assignment questions have also been added to enable the students to master the theory and art of financial management.', '9789834721138', 'Financial Management (3rd Edition).jpg', 'Shah Alam, Selangor', '62'),
(36, 'FINANCIAL MARKETS & INSTITUTIONS', 'Social Science', '2010-01-01', 'FREDERIC S.MISHKIN STANLEY G.EAKINS', 'Financial Markets and Institutions takes a practical approach to the changing landscape of financial markets and institutions. Best-selling authors Frederic S. Mishkin and Stanley G. Eakins use core principles to introduce students to topics, then examine these models with real-world scenarios. Empirical applications of themes help students develop essential critical-thinking and problem-solving skills, preparing them for future careers in business and finance', '0-321-30812-3', 'FINANCIAL MARKETS & INSTITUTIONS.jpg', 'USA', '0'),
(37, 'FOCUS SPM Prinsip Perakaunan Tingkatan 4-5 KSSM', 'Technology', '2020-11-01', 'Dr. Hooi Lai Wan & Tee Kok Bin', 'Siri teks rujukan yang lengkap dan padat dengan ciri-ciri istimewa untuk meningkatkan pembelajaran murid secara menyeluruh. Siri ini merangkumi Kurikulum Standard Sekolah Menengah (KSSM) yang baharu serta mengintegrasi dengan keperluan Sijil Pelajaran Malaysia (SPM). Pastinya satu sumber yang hebat bagi setiap murid! Reviews', '9789830087801', 'FOCUS SPM Prinsip Perakaunan Tingkatan 4-5 KSSM.jpg', 'Shah Alam, Selangor', '31'),
(38, 'Fundamentals of Communication Systems, Global Edition 2nd Edition', 'Technology', '2014-08-14', ' Proakis, John G. & Masoud Salehi', 'This text introduces the basic techniques used in modern communication systems and provides fundamental tools and methodologies used in the analysis and design of these systems. The authors emphasize digital communication systems, including new generations of wireless communication systems, satellite communications, and data transmission networks. A background in calculus, linear algebra, basic electronic circuits, linear system theory, and probability and random variables is assumed.', '9781292015682', 'Fundamentals of Communication Systems, Global Edition 2nd Edition.jpg', 'United Kingdom', '0'),
(39, 'A Winning System In Good Times Or Bad', 'Social Science', '2009-06-08', 'WILLIAM O NEIL', 'Through every type of market, William J. O Neils national bestseller, How to Make Money in Stocks, has shown over 2 million investors the secrets to building wealth. O Neils powerful CAN SLIM Investing System a proven 7 step process for minimizing risk and maximizing gains has influenced generations of investors.', '007137361-6', 'A Winning System In Good Times Or Bad.jpg', 'KUALA LUMPUR', '44'),
(40, 'GARIS PANDUAN LANDSKAP NEGARA', 'Art', '2008-01-01', 'MAZIFAH BINTI SIMIS MOHD SALLEH MAHMOOD', 'Garis Panduan Landskap Negara edisi 2 (GPLN 2), tahun 2008 adalah merupakan semakan semula serta penambahbaikan ke atas Garis Panduan Landskap Negara yang telah diterbitkan pada tahun 1995. Penerbitan Garis Panduan Landskap Negara, 1995 oleh Unit Landskap, pada ketika itu di bawah Jabatan Perancangan Bandar dan Desa (JPBD) adalah dibuat berdasarkan keputusan kerajaan supaya satu buku garis panduan yang lengkap berkenaan cara mewujud serta memelihara landskap yang cantik dan sempurna dapat diterbitkan', '978-967-5375-00-2', 'GARIS PANDUAN LANDSKAP NEGARA.jpg', 'KUALA LUMPUR', '0'),
(41, 'Guide to Networking Essentials (MindTap Course List) 8th Edition', 'General', '2019-01-01', 'Tomsho, Greg ', 'Equips students with the knowledge, skills and confidence needed to work with network infrastructure devices and network operating systems in a small to midsize network environment. Focusing on troubleshooting and computer networking technologies, it delivers a comprehensive, reader-friendly introduction to network protocols and network devices, including wireless and cybersecurity technologies. ', '9780357118283', 'Guide to Networking Essentials (MindTap Course List) 8th Edition.jpg', 'United States', '730'),
(42, 'Human Resource Management A Contemporary Approach (8th)', 'Technology', '2017-07-18', 'Beardwell, Julie / Thompson, Amanda', 'This highly engaging, bestselling textbook, now in its eighth edition offers a comprehensive examination of contemporary human resource management issues and debates. Aimed at undergraduate, postgraduate and MBA students, this title provides an authoritative source for students of CIPD Advanced qualifications.', '9781292119564', 'Human Resource Management A Contemporary Approach (8th).jpg', 'United Kingdom', '110'),
(43, 'HVAC Design Sourcebook, Second Edition', 'Technology', '2020-06-09', 'Angel, W. Larsen ', 'This fully updated guide covers the entire HVAC system design process from concept to commissioned systems. Written by a recognized HVAC expert, the book illustrates each step through photographs, drawings, and comprehensive discussions. This new edition has been completely refreshed to align with current industry standards and includes several brand-new chapters. HVAC Design Sourcebook, Second Edition contains a chapter-long case study that provides a step-by-step look at the design of a real-world HVAC project. ', '9781260457247', 'HVAC Design Sourcebook, Second Edition.jpg', 'United States', '0'),
(44, 'HVAC Water Chillers and Cooling Towers', 'Technology', '2003-04-04', 'Herbert W. Stanford III', 'HVAC Water Chillers and Cooling Towers provides fundamental principles and practical techniques for the design, application, purchase, operation, and maintenance of water chillers and cooling towers.', '9781138071711', 'HVAC Water Chillers and Cooling Towers.jpg', 'London ; New York', '650'),
(45, 'INTEGRATED ACCOUNTING', 'Technology', '2014-01-31', 'DALE H.KLOOSTER  WARREN W. ALLEN', 'Packed with step-by-step instructions, INTEGRATED ACCOUNTING + GL CD, 8e thoroughly explains computerized accounting and operating procedures for all Windows-based programs. The general ledger software emulates commercial software packages and gradually introduces software through opening balance files, demonstrating how to process ongoing accounting systems. As a result, readers learn accounting topics while gaining software experience.', '0-324-19139-1', 'INTEGRATED ACCOUNTING.jpg', 'USA', '0'),
(46, 'International Business Environments & Operations', 'Technology', '2021-05-19', 'Danials, J.D', 'International Business: Environments and Operations, 17th Edition, Global Edition, by John D. Daniels, Daniel Sullivan, and Lee H. Radebaugh remains one of the most authoritative texts available on the subject. Striking a balance between integrated theory and meaningful practice, the authors help deepen your understanding using modern scenarios, examples and cases. Chapters develop your critical thinking skills by encouraging you to apply what you have learned. Ideal for courses in international business, this edition includes the latest information on relevant political, economic, social, and institutional changes.  With a range of features to benefit your learning, this practical text will enhance your understanding of international business and help you succeed in your course.', '9781292403274', 'International Business Environments & Operations.jpg', 'Harlow', '115'),
(47, 'ISLAM AND CIVILIZATIONAL DIALOGUE  THE QUEST FOR A TRULY UNVERSAL CIVILIATION', 'Geography & History', '1997-01-01', 'OSMAN BAKAR', 'The central theme of the book is Islamʹs past, present and future dialogues with other cultures and civilizations. Islam has made a positive and major contribution to the development of the idea of a universal human civilization and to the enrichment of global human culture through its constructive civilizational engagement with the rest of the world. The author argues that, on the basis of its past achievements, Islam has both the necessary sense of civilizational mission and sufficient spiritual and intellectual means to conduct a world-wide conversation not only with its sister religions in the Abrahamic family, namely Judaism and Christianity but also with Far Eastern religions like Confucianism, Buddhism and even Shintoism in the pursuit of a truly universal civilization and a global ethics based on shared spiritual, moral and ethical values', '983-100-040-4', 'ISLAM AND CIVILIZATIONAL DIALOGUE  THE QUEST FOR A TRULY UNVERSAL CIVILIATION.jpg', 'KUALA LUMPUR', '0'),
(48, 'ISLAM AND CONFUCIANISM  A CIVILIZATIONAL DIALOGUE', 'Religion', '1997-01-01', 'OSMAN BAKAR', 'THE CONTENT of this book is comprised of a selection of papers that were originally presented at the historic International Seminar on Civilizational Dialogue between Islam and Confucianism, held at the University of Malaya, Kuala Lumpur on 13-15 March 1995. Written by a group of distinguished scholars of Islam and Confucianism, social activists, and ideologues of inter-religious and inter-civilizational dialogue, the book covers a wide range of topics related to the central theme of past and present encounters and interactions between Islam and Confucianism, and the future prospect of a more energetic and creative dialogue between the two religions and civilizations. ', '9831000382', 'ISLAM AND CONFUCIANISM  A CIVILIZATIONAL DIALOGUE.jpg', 'KUALA LUMPUR', '0'),
(49, 'JOM BINA APLIKASI ANDROID MENGGUNAKAN APP INVENTOR', 'General', '2019-01-01', 'Muhammad Rais Abd Halim', 'Aplikasi android sekarang menjadi suatu yang penting bagi memenuhi keperluan pembelajaran, pekerjaan serta kehidupan sekarang. Pembangunan aplikasi android menggunakan App Inventor amat mudah tanpa mempelajari pengaturcaraan. Seseorang boleh membina aplikasi android ringkas hanya dalam 10 minit sahaja. Berbantu buku ini, seseorang boleh membuat pelbagai aplikasi android dengan lebih mudah.  Buku ini disusun dengan begitu lengkap dan mudah difahami. Penerangan yang terperinci serta dibantu dengan rajah-rajah menunjukkan langkah demi langkah membina aplikasi android. Buku ini boleh dibaca oleh anak-anak seawal umur 10 tahun dan amat sesuai kepada mereka yang berminat dalam membangunkan aplikasi android. Pembaca didehkan dengan kepelbagaian kefungsian yang terdapat pada App Inventor.', '9789672306757   (9789672389729 : E-isbn)', 'JOM BINA APLIKASI ANDROID MENGGUNAKAN APP INVENTOR.jpg', 'Batu Pahat, Johor', '34'),
(50, 'Jom Cari Kerja!', 'Technology', '2013-03-01', 'Hj Azmi Bin Hj Abu Bakar', 'Semua perkongsian dalam buku ini sama pentingnya sama ada dari peringkat awal penyediaan resume sehinggalah pengetahuan tentang hak anda sebagai pekerja selepas diterima bekerja di mana-mana organisasi. Anda disarankan supaya membaca buku ini sekurang-kurangnya tiga kali khususnya mengenai contoh-contoh soalan temuduga agar anda berupaya menjawab soalan-soalan tersebut dengan penuh keyakinan dan sebaik mungkin. Cuba latih soalan-soalan tersebut dengan beberapa orang rakan seolah-olah anda membuat latihan lakonan dan rakan anda menjadi penemuduga manakala anda cuba menjawabnya. Buku ini lengkap dengan info yang padat dan terkini tentang proses mendapatkan pekerjaan secara teratur, lakaran dan gambar rajah serta contoh-contoh yang relevan, bahasa yang santai, perkongsian pengalaman industri dan organisasi yang praktikal serta percaturan teknik NLP.', '9789673881161', 'Jom Cari Kerja!.jpg', 'Kuala Lumpur', '10'),
(51, 'Kejayaan Dalam Keusahawanan', 'Social Science', '2020-01-01', 'Diyana Kamarudin', 'Buku ini boleh dijadikan sebagai panduan dan rujukan kepada semua pelajar yang ingin bergelar usahawan. Dalam membantu para pelajar menjadi usahawan berjaya, buku ini mengumpulkan sumbangan buah fikiran daripada penulis berpengalaman yang mampu memberi dorongan serta memotivasikan pelajar untuk menceburi bidang keusahawanan dan perniagaan. Buku ini juga mengandungi beberapa kompenen yang diperlukan untuk menjadi seorang usahawan yang berjaya. Ini termasuklah mengapa ramai yang memilih untuk menjadi usahawan, peranan keusahawanan, kemahiran keusahawanan dan kompetensi, etika, kreativiti dan inovasi, reka bentuk berfikir, cara untuk mencari peluang perniagaan, kanvas model perniagaan, pelan perniagaan yang termasuk perancangan kewangan, pengurusan projek dalam keusahawanan, pemasaran digital dan di mana untuk mendapatkan bantuan untuk pembiayaan dan inisiatif pembiayaan lain. Semoga buku ini dapat dijadikan panduan dalam membantu usahawan baharu serta pelajar dalam memahami konsep-konsep', '9789672226727', 'Kejayaan Dalam Keusahawanan.jpg', 'Kuantan, Pahang', '25'),
(52, 'Keselamatan dan Kesihatan Pekerjaan Di Tapak Pembinaan', 'Technology', '2018-01-01', 'Anuar Ithnin', 'Pengetahuan penting dalam menjaga kebajikan pekerja di tapak pembinaan.', '9789834913755', 'Keselamatan dan Kesihatan Pekerjaan Di Tapak Pembinaan.jpg', 'Selangor', '32'),
(53, 'Kuasai Perniagaan Internet SIRI 1', 'Technology', '2016-01-01', 'Wan Nong Muzafar', 'Buku teks digital untuk pengajian Keusahawanan Digital skim Teknikal Vokasional (TVET). Buku digital ini boleh dibaca menggunakan sistem operasi Android, iOS, Windows Phone & Desktop, dan browser Chrome. Buku ini amat sesuai untuk mereka yang baru berjinak-jinak dalam perniagaan online mahupun yang sedang berniaga dalam usaha memahami kaedah penjualan produk atau perkhidmatan selain mampu meluaskan potensi sasaran pelanggan digital di Malaysia dan di luar negara.', '9789678606493', 'Kuasai Perniagaan Internet SIRI 1.jpg', 'Shah Alam, Selangor', '26'),
(54, 'Kuasai Perniagaan Internet Siri 3', 'Technology', '2018-01-01', 'Wan Nong Muzafar', 'Kenapa anda perlu memiliki buku ini?  Ini adalah buku terakhir dalam siri keusahawanan KUASAI PERNIAGAAN INTERNET. Setelah menguasai setiap komponen yang ada dalam perniagaan internet, anda seharusnya sudah tahu bagaimana untuk menangani setiap masalah dalam perniagaan anda.  Walau bagaimanapun, bijak membuat copywriting, bijak menguruskan database pelanggan, bijak mempromosi dan mengiklankan perniagaan anda, tak semestinya anda juga bijak MENGANALISA kewangan perniagaan anda. Ramai usahawan yang gagal dalam bab ini. Maka, jangan terkejut jika perniagaan anda tetap statik tidak berkembang maju atau lebih teruk lagi, merosot dan terus merosot…  Semoga perniagaan anda tidak dalam kategori itu!!!', '9789678608305', 'Kuasai Perniagaan Internet Siri 3.jpg', 'Shah Alam, Selangor', '26'),
(55, 'Landscape Architecture Documentation Standards  Principles, Guidelines and Best Practices', 'Art', '2015-12-02', 'Designworkshop', 'A project will only be built as well as it is documented. This publication focuses on the key documentation needs of the landscape architectural design and construction documentation process. That includes both \"design documentation\" and \"construction documentation\" as well as all that which occurs in the transition from one phase to the other.  Documentation requirements include those components necessary to explore and define design intent, logic, physical proposals, and ultimately, the specific components included within construction and bid documents.', '9780470402177', 'Landscape Architecture Documentation Standards  Principles, Guidelines and Best Practices.png', 'Hoboken, New Jersey ', '400'),
(56, 'Landscape Garden Series Planting and Maintenance', 'Art', '2018-02-02', 'Lawrence, Charles H. ', 'The importance of providing careful direction and guidance in growth cannot be overestimated. All planning is done with an idea in mind. When the idea is carried out in the actual arrangement of land and landscape, the forces of man and nature must combine if the idea and purpose of the design is to be realized. A place carefully planned and laid out never offers the best appearance if it is not properly maintained throughout the year.', '9780267627219', 'Landscape Garden Series Planting and Maintenance.jpg', 'London', '165'),
(57, 'MANAGEMENT INFORMATION SYSTEMS  MANAGING THE DIGITAL FIRM', 'Technology', '2019-08-02', 'KENNETH C. LAUDON JANE P. LAUDON', 'The authoritative, case-based study of IS in business today Management Information Systems: Managing the Digital Firm provides the most comprehensive overview of information systems used by business firms today, while drawing connections between MIS and business performance. The Laudons are known for their outstanding real-world case studies, which describe how well-known companies use IT to solve problems and achieve business objectives. Students develop sought-after skills, such as leading IS-related management discussions and using IT to meet bottom-line results. Each chapter of the 16th edition features all-new Interactive Sessions, new Video Cases, and a new Career Opportunities section building practical job-seeking skills.', '0-13-120681-8', 'MANAGEMENT INFORMATION SYSTEMS  MANAGING THE DIGITAL FIRM.jpg', 'United States', '0'),
(58, 'MANAGERIAL ACCOUNTING', 'Technology', '2010-01-01', 'GARRISON H.RAY', ' For centuries, the lighthouse has provided guidance and safe passage for sailors. Similarly, Garrison/Noreen/Brewer has successfully guided millions of students through managerial accounting, helping them sail smoothly through the course. Decades ago, lighthouses were still being operated manually. In these days of digital transformation, lighthouses are run using automatic lamp changers and other modern devices. In much the same way, Garrison/ Noreen/Brewer has evolved over the years. Today, the Garrison book not only guides students—accounting majors and non-majors alike— safely through the course, but is enhanced by new forms of media and technology to augment student learning and increase student motivation. McGraw-Hill Connect Accounting allows instructors to build assignments and tests from static and algorithmic versions of the end-of-chapter material and testbank problems. Integrated iPod content allows students to download lecture presentations, videos, and self-quizzes to th', '0-256-16917-9', 'MANAGERIAL ACCOUNTING.jpg', 'WASHINGTON', '0'),
(59, 'Marketing Management 15th Edition', 'Technology', '2014-12-30', 'Kotler, Philip and Kevin Lane Keller', 'The gold standard for today’s marketing management student. Stay on the cutting-edge with the gold standard text that reflects the latest in marketing theory and practice. The world of marketing is changing everyday–and in order for students to have a competitive edge, they need a textbook that reflects the best of today’s marketing theory and practices.Marketing Management is the gold standard marketing text because its content and organization consistently reflect the latest changes in today’s marketing theory and practice. The Fifteenth edition is fully integrated with MyMarketingLab and is updated where appropriate to provide the most comprehensive, current, and engaging marketing management text as possible.  ', '9781292092621', 'Marketing Management 15th Edition.jpg', 'United Kingdom', '100'),
(60, 'Marketing Management, Global Edition 16th Edition', 'Technology', '2021-11-24', 'Kotler, Philip &   Keller, Kevin ', 'The gold standard for today’s marketing management student The world of marketing is changing every day ― and in order for students to have a competitive edge, they need a text that reflects the best and most recent marketing theory and practices. Marketing Management collectively uses a managerial orientation, an analytical approach, a multidisciplinary perspective, universal applications, and balanced coverage to distinguish itfrom all other marketing management texts out there. Unsurpassed in its breadth,depth, and relevance, the 16th Edition features a streamlined organization of the content, updated material, and new examples that reflect the very latest market developments. After reading this landmark text, students will be armed with the knowledge and tools to succeed in the new market environment around them.', '9781292404813', 'Marketing Management, Global Edition 16th Edition.jpg', 'United Kingdom', '107'),
(61, 'Mastering AutoCAD 2019 And AutoCAD LT 2019', 'Technology', '2018-06-01', 'George Omura Brian C. Benton ', 'Mastering AutoCAD 2019 and AutoCAD LT 2019 is the world’s all-time best-selling guide to the world’s most popular drafting software. Packed with tips, tricks, techniques, and tutorials, this guide covers every inch of AutoCAD and AutoCAD LT—including certification. This new edition has been fully updated to align with the software’s 2019 update, featuring the same expert instruction augmented by videos of crucial techniques. Step-by-step walk-throughs, concise explanations, specific examples and plenty of hands-on projects help you learn essential AutoCAD skills by working directly with the necessary tools—giving you a skill set that translates directly to on-the-job use.  AutoCAD is the dominant design and drafting software for 2D and 3D technical drawings, while AutoCAD LT is the more affordable version often used by students and hobbyists. Professional designers need complete command of the software’s tools and functions, but a deeper exploration of more complex capabilities can hel', '9781119495000', 'Mastering AutoCAD 2019 And AutoCAD LT 2019.jpg', 'Indianapolis, Indiana', '314'),
(62, 'Membina Laman Web Menggunakan CMS', 'General', '2013-01-01', 'Azizul Zamri Muhamed Amin,  Mohamad Aizi Salamat,  Mohd Zaki Mohd Salikon, Mohd Norasri Ismail and M', 'Buku ini mengandungi 8 topik langkah demi langkah dari penyediaan isi kandungan laman web hinggalah kepada memasukkan modul-modul dan komponen-komponen untuk membina laman web CMS. Ini untuk memastikan pembaca dapat memahami dan seterusnya menggunakan langkah-langkah yang diberi sebagai panduan untuk membina laman web CMS ini nanti. Selain itu, setiap langkah disertakan gambarajah bagi menunjukkan gambaran yang sebenar apa yang perlu dilakukan oleh pembaca semasa membina laman web CMS ini.', '9789670468099', 'Membina Laman Web Menggunakan CMS.jpg', 'Johor Bahru', '31'),
(63, 'Memulakan Bisnes Sendiri (Edisi Kemaskini)', 'Technology', '2007-07-03', 'Ainon Mohd ', 'Buku ini dikemas kini daripada segi bahasa dan susun atur bagi meningkatkan penampilan dan kualitinya. Buku ini memberi panduan dan tip kepada sesiapa sahaja yang berminat memulakan perniagaan sendiri. Antara perkara menarik yang disentuh di dalam buku ini seperti bagaimana memilih calon isteri untuk usahawan, bagaimana memilih syarikat dan sektor bisnes, bagaimana memilih rakan kongsi dan bagaimana syarikat dirompak dan perkara baik yang membahayakan.', '9789674810351', 'Memulakan Bisnes Sendiri (Edisi Kemaskini).jpg', 'Batu Caves, Selangor', '40'),
(64, 'MICROSOFT OFFICE 2000  INTRODUCTORY CONCEPTS AND TECHNIQUES', 'Technology', '1999-07-29', 'GARY B. SHELLY', 'Part of the highly successful Shelly Cashman Series, this text offers a clear step-by-step, screen-by-screen approach to learning basic Microsoft Office 2000 skills. Following the success of our best-selling Office 97 text, this text includes up to date coverage of Windows 98, Word 2000, Excel 2000, Access 2000, and PowerPoint 2000. It also emphasizes Office 2000 Help, publishing Web pages, use of hyperlinks, and Web queries.', '0-7895-4635-3', 'MICROSOFT OFFICE 2000  INTRODUCTORY CONCEPTS AND TECHNIQUES.jpg', 'USA', '66'),
(65, 'Mikroekonomi', 'Social Science', '2019-01-01', 'Lim Faith', 'Dihasilkan untuk memenuhi keperluan khusus pelajar STPM yang menginginkan buku ulang kaji yang mengetengahkan nota yang padat dan latihan yang mencabar.  Buku ini diyakini dapat membantu pelajat untuk mengingati fakta-fakta penting dan membina kemahiran menjawab soalan.', '9789674937485', 'Mikroekonomi.jpg', 'Petaling Jaya, Selangor', '16'),
(66, 'MONEY AND BANKING IN MALAYSIA', 'Social Science', '1984-01-01', 'BANK NEGARA', 'N/A', 'N/A', 'MONEY AND BANKING IN MALAYSIA.jpg', 'Kuala Lumpur', '0'),
(67, 'City of Ellora: Infinitium White ', 'Literature', '2022-09-10', 'Jimmy Tran', 'Deceit, bloodshed, and cruelty. In battle, we all are heroes. With different banners and guides for our weapons, we set forth. Murder, malice, and elegance. In pursuit, the adventurers from Ellora chased after a monster in red. The adventurers belong to Scarlet Spring. What began with a hunt for a serial killer led to disaster. Blood splattered around. Cities razed to barren ground. Flesh and bones are torn asunder by fiends of monsters and men. They were not the only ones in pursuit. Armies and the gods arrived with intentions unknown to follow suit. Piece by piece, their world known as Torsamel would become enraptured in the chaos and carnage. Follow as the characters from Scarlet Spring fight their own shadows, dance with steel, and find themselves down a path toward ruination. Their journey would wrench out their own hearts. With a single pluck of a string, their mission, their hunt, would unveil threats never before seen.', '979-8351611440', 'City of Ellora: Infinitium White .jpg', 'New York', '68'),
(68, 'A Man Called Ove: A Novel', 'Literature', '2015-05-05', ' Fredrik Backman', '#1 New York Times bestseller—more than 3 million copies sold!  Meet Ove. He’s a curmudgeon—the kind of man who points at people he dislikes as if they were burglars caught outside his bedroom window. He has staunch principles, strict routines, and a short fuse. People call him “the bitter neighbor from hell.” But must Ove be bitter just because he doesn’t walk around with a smile plastered to his face all the time?  Behind the cranky exterior there is a story and a sadness. So when one November morning a chatty young couple with two chatty young daughters move in next door and accidentally flatten Ove’s mailbox, it is the lead-in to a comical and heartwarming tale of unkempt cats, unexpected friendship, and the ancient art of backing up a U-Haul. All of which will change one cranky old man and a local residents’ association to their very foundations.  Fredrik Backman’s beloved first novel about the angry old man next door is a thoughtful exploration of the profound impact one life has ', '978-1476738024', 'A Man Called Ove: A Novel.jpg', 'Washington', '59'),
(69, 'The Midnight Library: A Novel', 'Literature', '2020-09-29', ' Matt Haig', 'Somewhere out beyond the edge of the universe there is a library that contains an infinite number of books, each one the story of another reality. One tells the story of your life as it is, along with another book for the other life you could have lived if you had made a different choice at any point in your life. While we all wonder how our lives might have been, what if you had the chance to go to the library and see for yourself? Would any of these other lives truly be better?', '978-0525559474', 'The Midnight Library: A Novel.jpg', 'United Kingdom', '34'),
(70, 'Genetics: A Conceptual Approach Seventh Edition', 'Pure Science', '2019-12-27', 'Benjamin Pierce', 'With Genetics: A Conceptual Approach, Ben Pierce brings a master teacher’s experiences to the introductory genetics textbook, clarifying this complex subject by focusing on the big picture of genetics concepts and how those concepts connect to one another.', '978-1319216801', 'Genetics: A Conceptual Approach Seventh Edition.jpg', 'United States', '110'),
(71, 'Lehninger Principles of Biochemistry 8th Edition', 'Pure Science', '2021-01-01', 'David L. Nelson', 'Lehninger’s Principles of Biochemistry earned acclaim for its presentation and organization of complex concepts and connections, anchored in the principles of biochemistry.  This legacy continues in the eighth edition with a new framework that highlights the principles and supports student learning.', '978-1319228002', 'Lehninger Principles of Biochemistry 8th Edition.jpg', 'United States', '246'),
(72, 'Learn Korean – The Language Workbook for Beginners:  An Easy, Step-by-Step Study Book and Writing Pr', 'Language', '2021-03-05', 'Jennie Lie', 'Our comprehensive workbook for beginners makes learning Korean simple! **NOW UPDATED** Packed with practical information and easy, step-by-step guides to help you read, write, and speak Korean faster:  Ideal Introduction to the Korean Language Learn all about the historic Hangul Alphabet Complete Stroke Order Diagrams and Writing Instruction Hangul flashcard template pages to cut out and keep Over 150+ pages, with Calligraphy Practice and Quizzes! Detailed Guide to Pronunciation and Rules This Korean book is suitable for adults and kids, from total beginners to those looking to improve their writing Hangul writing skills. Our self-study exercises and how-to-write style practice pages will simplify the whole process for elementary and intermediate Korean.', '978-1838291648', 'Learn Korean – The Language Workbook for Beginners:  An Easy, Step-by-Step Study Book and Writing Practice Guide for Learning How to Read, Write, and ... Inside!)  (Elementary Korean Language Books).jpg', 'South Korea', '70'),
(73, 'American Sign Language for Beginners: Learn Signing Essentials in 30 Days (American Sign Language Gu', 'Language', '2020-07-28', 'Rochelle Barlow', 'There’s an easy way to leap right in to learning American Sign Language (ASL). American Sign Language for Beginners delivers 30 days of lessons that will help you sign with those in your home, community, and classroom.  From letters and numbers to essential vocabulary and grammar basics, this beginner’s guide provides the essentials needed to develop a solid foundation for American Sign Language in the real world. Each daily lesson takes less than 30 minutes to complete and focuses on a single set of vocabulary or ASL grammar. Throughout the course, you’ll find key phrases, helpful memory tips, signing practice activities, and insight into deaf culture. Start your ASL masterclass today.', '978-1646116423', 'American Sign Language for Beginners: Learn Signing Essentials in 30 Days (American Sign Language Gu.jpg', 'Canada', '45');

-- --------------------------------------------------------

--
-- Table structure for table `borrow`
--

CREATE TABLE `borrow` (
  `ID` int(11) NOT NULL,
  `BookFK` int(11) NOT NULL,
  `UserFK` int(11) NOT NULL,
  `FromDate` date NOT NULL,
  `ToDate` date NOT NULL,
  `IsBillSettled` tinyint(1) NOT NULL,
  `Status` varchar(1) NOT NULL COMMENT 'B - borrowed; R - Returned'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `borrow`
--

INSERT INTO `borrow` (`ID`, `BookFK`, `UserFK`, `FromDate`, `ToDate`, `IsBillSettled`, `Status`) VALUES
(9, 4, 1, '2023-01-26', '2023-01-27', 0, ''),
(10, 18, 18, '2023-01-26', '2023-01-31', 0, '');

-- --------------------------------------------------------

--
-- Table structure for table `receipt`
--

CREATE TABLE `receipt` (
  `ID` int(11) NOT NULL,
  `BorrowFK` int(11) NOT NULL,
  `LateDay` int(11) NOT NULL,
  `Penalty` float NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `receipt`
--

INSERT INTO `receipt` (`ID`, `BorrowFK`, `LateDay`, `Penalty`) VALUES
(1, 9, 0, 0),
(2, 10, 4, 0);

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `ID` int(11) NOT NULL,
  `Email` varchar(100) NOT NULL,
  `Password` varchar(100) NOT NULL,
  `Street` varchar(100) NOT NULL,
  `Zip` int(11) NOT NULL,
  `State` varchar(100) NOT NULL,
  `FullName` varchar(100) NOT NULL,
  `UitmID` int(11) NOT NULL,
  `IsAdmin` tinyint(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`ID`, `Email`, `Password`, `Street`, `Zip`, `State`, `FullName`, `UitmID`, `IsAdmin`) VALUES
(1, '2022828866@my', 'Test123', 'Jalan abc', 400000, 'Selangor', 'Sven Frei', 0, 0),
(2, '2022828866@my.my', 'test', 'Jalan abc', 400000, 'Selangor', 'Sven Frei', 0, 0),
(3, '2022828866@student.uitm.edu.my', 'Test123', 'Jalan abc', 400000, 'Selangor', 'Sven', 0, 0),
(4, '2022828866@student.uitm.edu.myy', 'Test', 'Jalan abc', 400000, 'Selangor', 'Sven', 0, 0),
(6, '2022828866@student.uitm.edu.myyy', 'Test', 'Jalan abc', 400000, 'Selangor', 'Sven', 0, 0),
(8, '2022828866@test.my', 'Test', 'Jalan abc', 400000, 'Selangor', 'Sven', 0, 0),
(11, 'test@me.my', 'test', 'Jalan abc', 400000, 'Selangor', 'Sven', 0, 0),
(13, 'test@student.uitm.edu.myy', 'test', 'Jalan abc', 400000, 'Selangor', 'Sven', 0, 0),
(16, 'frei-sven@bluewin.ch', 'test', 'Nelkenweg', 8360, 'Thurgau', 'Sven Frei', 2022828867, 0),
(17, 'arifazman011@gmail.com', 'aaa', 'Astaka', 41050, 'Selangor', 'Arif Azman', 2021619936, 1),
(18, '2020496204@student.uitm.edu.my', '123456', '16, JLN TENGKU AMPUAN JEMAAH 9/13, SEKSYEN 9, SHAH ALAM', 40100, 'SELANGOR', 'NUR HIDAYAH BINTI ISHAK', 2020496204, 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `book`
--
ALTER TABLE `book`
  ADD PRIMARY KEY (`ID`);

--
-- Indexes for table `borrow`
--
ALTER TABLE `borrow`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `BookFK` (`BookFK`),
  ADD KEY `UserFK` (`UserFK`);

--
-- Indexes for table `receipt`
--
ALTER TABLE `receipt`
  ADD PRIMARY KEY (`ID`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`ID`),
  ADD UNIQUE KEY `Email` (`Email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `book`
--
ALTER TABLE `book`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=74;

--
-- AUTO_INCREMENT for table `borrow`
--
ALTER TABLE `borrow`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

--
-- AUTO_INCREMENT for table `receipt`
--
ALTER TABLE `receipt`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=19;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `borrow`
--
ALTER TABLE `borrow`
  ADD CONSTRAINT `borrow_ibfk_1` FOREIGN KEY (`BookFK`) REFERENCES `book` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION,
  ADD CONSTRAINT `borrow_ibfk_2` FOREIGN KEY (`UserFK`) REFERENCES `user` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
